[project]
name = "ws26_industrial_datascience_manuscript"
version = "0.1.0"
description = "Industrial Data Science Manuscript"
authors = [
    { name = "Gregor Ehrensperger", email = "g@ehrensperger.dev" },
]
requires-python = ">=3.13"
readme = "README.md"
license = { text = "-" }
dependencies = [
    "quarto-cli>=1.7.33",
]

[dependency-groups]
dev = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.1",
    "plotly>=6.3.0",
    "scikit-learn>=1.7.1",
    "seaborn>=0.13.2",
    "sktime>=0.40.0",
    "statsmodels>=0.14.5",
    "tslearn>=0.6.3",
    "scipy>=1.16.3",
    "yfinance>=0.2.66",
    "tensorflow>=2.20.0",
    "torch>=2.10.0",
]

[tool.ruff]
line-length = 120
