# Self study - Session 3 {#sec-act1-selfstudy3}

In this session, we will revisit the chapters @{sec-act1-clustering}, @{sec-act1-classification}, and @{sec-act1-regression}.

We have seen that the algorithms for all three tasks more or less can be categorized into the same categories:

- Based on distances or metrics: E.g. trees and forests
- Based on distributions, kernels: E.g. Gaussian Mixture Models, SVMs
- Based on subsequences, shapelets: E.g. bags of words, shapelet-based methods
- Based on deep learning: E.g. recurrent neural networks, or treating the time series as images using CNNs
- Based on random convolutions: E.g. _Random Convolutional Kernel Transform_ (ROCKET)
- Based on ensembles of the above.

We have implemented nearest neighbors (distance-based) for clustering, time series forests (distance-based) for classification, and convolutional neural networks for regression (deep learning-based).

Let us have a look at one additional algorithm for each task.

::: {.callout-note}
You can use `sktime`'s `load_UCR_UEA_dataset` function to load the data sets mentioned below, e.g.
```python
from sktime.datasets import load_UCR_UEA_dataset

ds_name = "UWaveGestureLibrary"
ret_type = "numpy3d"

X_train, y_train = load_UCR_UEA_dataset(
    name=ds_name,
    split="train",
    return_type=ret_type,
)

X_test, y_test = load_UCR_UEA_dataset(
    name=ds_name,
    split="test",
    return_type=ret_type,
)

# For classification, convert y to categorical
y_train = pd.Series(y_train).astype("category")
y_test = pd.Series(y_test).astype("category")
```
:::

::: {.callout-caution appearance="simple" collapse="true" icon=false}
::::{#exr-basics-mv-space}
## Clustering with time series DBScan
::::
- Load the [`GesturePebbleZ1`](https://timeseriesclassification.com/description.php?Dataset=GesturePebbleZ1) data set. Note that it is a variable-length time series dataset and you need to either use `ret_type="df-list"` or `ret_type="nested_univ"` to load it (using the example above).
- Bring the data into a suitable format and explore the data set visually (using plots).
- Use the Time Series $k$ means algorithm to cluster the data. Do you need to reshape the data for this algorithm?
- Now, try to use the time series DBScan algorithm for clustering. Do you need to reshape the data for this algorithm?
- How do the results compare?
:::

In @{sec-act1-classification} and @{sec-act1-regression}, our input was univariate, meaning each sample consisted of exactly one time series.
Now, we will work with multivariate time series, which are more common in real-world scenarios since typically multiple sensors are available.

::: {.callout-caution appearance="simple" collapse="true" icon=false}
::::{#exr-basics-mv-space}
## Classification of multivariate time series
::::
- Load the [`UWaveGestureLibrary`](https://timeseriesclassification.com/description.php?Dataset=UWaveGestureLibrary) data set.
- Use the time series $k$ nearest neighbour algorithm to classify the time series.
- Use the CNN classifier to classify the time series (make sure to have `sktime>=0.40.0` installed).
- How do the results compare?
:::

Note that not all of the algorithms have implementations for multivariate time series, e.g. `sktime`'s `TimeSeriesForestClassifier` only works for univariate time series (and raises an exception when used with a multivariate series).
Luckily, there are other implementations available, e.g. `aeon` offers a `TimeSeriesForestClassifier` that is compatible with multivariate time series.


::: {.callout-note}
`aeon` is quite strict about dependencies.
In case you have problems installing it, consider to initialize a new project and first install `aeon` before adding further packages.
:::

::: {.callout-caution appearance="simple" collapse="true" icon=false}
::::{#exr-basics-mv-space}
## Classification using aeon's Time Series Forest Classifier
::::
- Load the [`UWaveGestureLibrary`](https://timeseriesclassification.com/description.php?Dataset=UWaveGestureLibrary) data set.
- Use `aeon`'s `TimeSeriesForestClassifier` to classify the data set.
- Are you able to achieve better results than with the previous algorithms?
:::

::: {.callout-note}
You can use `aeon`'s `load_regression` function to load the data set mentioned below, e.g.
```python
from aeon.datasets import load_regression

ds_name = "AppliancesEnergy"

X_train, y_train = load_regression(ds_name, split="train")
X_test, y_test = load_regression(ds_name, split="test")
```
:::

::: {.callout-caution appearance="simple" collapse="true" icon=false}
::::{#exr-basics-mv-space}
## Regression of multivariate time series
::::
- Load the [`AppliancesEnergy`](https://archive.ics.uci.edu/dataset/374/appliances+energy+prediction) data set.
- Use the time series $k$ nearest neighbour algorithm to predict the energy consumption of the appliances.
- Use the time series random forest tree algorithm to predict the energy consumption of the appliances.
- Use the CNN regressor to predict the energy consumption of the appliances (make sure to have `sktime>=0.40.0` installed).
- How do the results compare?
:::