# Self study - Session 4 {#sec-act2-selfstudy4}
In this session, we will generate a report from our findings.

During the exploratory data analysis in @{sec-act2-selfstudy3}, we have looked at a large number of visualizations and identified key patterns and insights using different approaches.
This is nice, but you want to report your results to your management in a concise manner, focus on key findings and make it easily digestible.

::: {.callout-caution appearance="simple" collapse="true" icon=false}
:::: {#exr-basics-mv-space}
## Jupyter Notebook Report
::::
Polish your document, only keep relevant insights, remove unnecessary details, focus on key findings, document with markdown cells and export the result as HTML or PDF (since your management most likely will not have JupyterLab installed).

1. PDF: The document will be a static version of your notebook, so make sure to include all relevant information and insights directly in the document.
1. HTML: The document will also be a static version of your notebook (the Dropdown would not work e.g.), but the interactivity of the `plotly` plots will still be available, since the HTML export retains the JavaScript functionality.
:::

The resulting exports are a good start, but you may want to enhance them further using [`Quarto`](https://quarto.org/).
Quarto is an open-source scientific and technical publishing system allowing to generate and configure dynamic documents, reports, presentations, and more.
It is even compatible with Jupyter notebooks and e.g. allows to collapse code chunks.

::: {.callout-caution appearance="simple" collapse="true" icon=false}
:::: {#exr-basics-mv-space}
## Quarto
::::
In the previous exercise, you have cleaned up your notebook and prepared for reporting.
Use Quarto to generate a more polished report of your findings.
Export your report as a PDF and HTML document

Use [this documentation](https://quarto.org/docs/tools/jupyter-lab.html) as a starting point.
:::

Also the material of this course is rendered using Quarto.
